# Generated by Django 5.1.4 on 2024-12-16 15:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryJewel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EARRINGS', 'Earrings'), ('BRACELET', 'Bracelet'), ('NECKLACE', 'Necklace'), ('COMBO', 'Combo')], default='EARRINGS', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonsJewel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall'), ('WINTER', 'Winter')], default='SUMMER', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jewels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('collection', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewels.collection')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewels.categoryjewel')),
                ('season_jewel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewels.seasonsjewel')),
            ],
        ),
    ]
