# Generated by Django 5.1.4 on 2024-12-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionJewel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(choices=[('AMALFI-2024', 'Amalfi-2024'), ('AMALFI-2025', 'Amalfi-2025'), ('XO-XO', 'XO-XO'), ('XO-XO SNOW', 'XO-XO SNOW')], default='AMALFI-2024', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='categoryjewel',
            name='type',
            field=models.CharField(choices=[('ОБЕЦИ', 'ОБЕЦИ'), ('ГРИВНИ', 'ГРИВНИ'), ('КОЛИЕТА', 'КОЛИЕТА'), ('КОМПЛЕКТИ', 'КОМПЛЕКТИ')], default='ОБЕЦИ', max_length=30),
        ),
        migrations.AlterField(
            model_name='seasonsjewel',
            name='season',
            field=models.CharField(choices=[('ПРОЛЕТ', 'ПРОЛЕТ'), ('ЛЯТО', 'ЛЯТО'), ('ЕСЕН', 'ЕСЕН'), ('ЗИМА', 'ЗИМА')], default='ЛЯТО', max_length=50),
        ),
    ]
