# Generated by Django 5.1.4 on 2024-12-17 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0002_collectionjewel_alter_categoryjewel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewels',
            name='collection_jewel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewels.collectionjewel'),
        ),
    ]
