# Generated by Django 5.1.4 on 2024-12-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0002_collection_jewels_image_jewels_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_season',
            new_name='season',
        ),
    ]
