# Generated by Django 5.1.4 on 2024-12-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0003_jewels_collection_jewel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewels',
            name='collection_jewel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewels.collectionjewel'),
        ),
    ]
