# Generated by Django 5.1.4 on 2024-12-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0003_rename_short_description_collection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewels',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewels.collection'),
        ),
    ]
