# Generated by Django 5.1.4 on 2024-12-18 21:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0004_alter_jewels_collection_jewel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewels',
            name='additional_image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='jewels',
            name='additional_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='collectionjewel',
            name='collection',
            field=models.CharField(choices=[('AMALFI-2024', 'AMALFI-2024'), ('AMALFI-2025', 'AMALFI-2025'), ('XO-XO', 'XO-XO'), ('XO-XO SNOW', 'XO-XO SNOW')], default='AMALFI-2024', max_length=30),
        ),
    ]
