# Generated by Django 5.1.4 on 2024-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0005_jewels_additional_image_1_jewels_additional_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
