# Generated by Django 5.1.4 on 2024-12-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0006_alter_collection_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
