# Generated by Django 5.1.4 on 2024-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0007_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
