# Generated by Django 5.1.4 on 2024-12-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0008_alter_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='materials_used',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
